development:
  adapter: sqlite3
  encoding: unicode
  database: mattmitchell
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  # host: <%= ENV['DATABASE_URL'] %>
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
